### ISSUE TITLE
libdlt.so.2: undefined symbol: dlt_receiver_receive_socket

### ISSUE THREAD

**Issue by Lawjune** [bmwcarit/python-dlt#13]
Hi dear BMW Car IT team,

First of all thank you so much for sharing this fantastic jobs.

I`ve installed libdlt2_2.18.0-1_amd64.deb, dlt-daemon_2.18.0-1_amd64.deb and dlt-tools_2.18.0-1_amd64.deb in my Ubuntu laptop, then I was trying to check your examples of DLTClient. Then python thrown this AttributeError as below. 

Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from dlt import dlt
>>> c = dlt.DLTClient(servIP="127.0.0.1")
>>> c.connect()
True
>>> dlt.dltlib.dlt_receiver_receive_socket(ctypes.byref(client.receiver))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/eesd-icv/anaconda3/lib/python3.7/ctypes/__init__.py", line 369, in __getattr__
    func = self.__getitem__(name)
  File "/home/eesd-icv/anaconda3/lib/python3.7/ctypes/__init__.py", line 374, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/x86_64-linux-gnu/libdlt.so.2: undefined symbol: dlt_receiver_receive_socket

Did I install the incorrect dlt related libraries? 
Thank you so much in advanced!
Luo Jun

**Comment by aigarius** [comment]
We have a task in progress to support 2.18 libdlt, but it is still being reviewed for release. There are some changes to C structures and functions that we need to use differently.

**Comment by Lawjune** [comment]
Thank you so much aigarius!

**Comment by Lawjune** [comment]
Hi Aigars,

Can you kindly share the way how to get the correct version of libdlt.so.2?

Thanks a lot,
Luo Jun

**Comment by aigarius** [comment]
The easiest way is to download DLT Daemon sources from https://github.com/GENIVI/dlt-daemon/releases/tag/v2.16.0 and compile them locally.

**Comment by Lawjune** [comment]
Cool! It works  now! Thank you so much!

**Comment by aigarius** [comment]
New version with v2.18 libdlt support is now merged.
