### ISSUE TITLE
DLTBroker - Receive messages via callback

### ISSUE THREAD

**Issue by damozt** [bmwcarit/python-dlt#17]
Hi!

I'm using the DLTBroker, and need slightly different behavior than saving all messages to a dlt file. I need to keep messages received in an in-memory list, and only keep messages that are within a range of time. I want to store the messages in a list, and only create the dlt file when I need to. Is there a way I can already do this, or can you provide any assistance as to how I might achieve this? Thanks for your time!

**Comment by aigarius** [comment]
That is what can be done with a DLTContext concept. The idea is that you have a separate thread or process where you would be processing the DLT messages your way, then you give to DLTContextHandler.register() a set of filters describing which messages you are interested in and a queue object and then DLTMessageHandler will put messages matching your filter into your queue and you can then do what you need with them. 

We use this internally to monitor messages to detect the device going trough its different stated (booting, all services up, in shutdown, crash handling active, ...). For performance reasons it is useful to limit the amount of messages you are interested in by APID/CTID paris.

**Comment by damozt** [comment]
Thanks for your quick response! 

I have attempted to use the context, but was unable to control and manipulate it how I can with a list. I may just need to gain more skill and knowledge using `Process` and `Queue`. Am I able to filter a Queue similar to how I can with a list?

The original idea is: Every message that comes in gets added to a list. The list is immediately filtered based on if it is within a range (let's say 2 minutes). And then, when I want to create a dlt file based on another range (shorter than 2 minutes), I filter those and do a `dlt.save(filtered_messages, file_path)` I added in logic that would callback to my code that would allow me to add each message to a list, but when I want to use that list outside of the background thread, the list was empty.

If you could provide any additional guidance on this, I would be extremely grateful! :D

**Comment by aigarius** [comment]
You should be consuming the messages out of the Queue and putting them into your own history list (and re-filtering it periodically, not on every message as there can be hundreds of messages per second, you only want to refilter if the second changed at most). It might also be necessary to use a lock from multithreading to protect concurrent access to your history list. I would recommend to keep all Python code as single-threaded as possible, however. Messages can wait their turn in the Queue while you are processing previous messages (at least for a little while until your Queue reaches its max size).

**Comment by damozt** [comment]
Thanks so much for your help! My issue was solved, and the software works wonderfully. 
Kudos to you and all of your contributors for this incredible library.

I replaced the default message handler with my own. I store each message received into an array in memory, and every 200 messages I filter the list to see if it is within my time frame, and save a temporary dlt file into /tmpfs. 

Possibly, an addition you could make to this is add an optional override for the message handler when initializing a DLTBroker? (instead of only using 'def handle' inside of DLTMessageHandler)
