### ISSUE TITLE
OSError: libdlt.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Grossman1987** [bmwcarit/python-dlt#18]
Hi,
first of all, I wanna thank you, that you share this project!

I tried to install the python-dlt in my venv (I'm on a Ubuntu 18.04 LTS in a WSL and have installed python 3.7) and get the following message if I do "from dlt import dlt".
Perhaps you have an idea why the libdlt.so.2 is not found (or created?)?
Thanks and regards!
grossman

```
/home/haerinjo/Projects/ectp/venv_ectp/bin/python /home/haerinjo/Projects/ectp/tools/python/AIT/AIT.py
Traceback (most recent call last):
  File "/home/haerinjo/Projects/ectp/tools/python/AIT/AIT.py", line 6, in <module>
    from dlt import dlt
  File "/home/haerinjo/Projects/ectp/venv_ectp/lib/python3.7/site-packages/dlt-2.1.dev2+g4b910df-py3.7.egg/dlt/dlt.py", line 17, in <module>
    from dlt.core import (
  File "/home/haerinjo/Projects/ectp/venv_ectp/lib/python3.7/site-packages/dlt-2.1.dev2+g4b910df-py3.7.egg/dlt/core/__init__.py", line 11, in <module>
    from dlt.core.core_base import *
  File "/home/haerinjo/Projects/ectp/venv_ectp/lib/python3.7/site-packages/dlt-2.1.dev2+g4b910df-py3.7.egg/dlt/core/core_base.py", line 7, in <module>
    dltlib = ctypes.cdll.LoadLibrary('libdlt.so.2')
  File "/usr/lib/python3.7/ctypes/__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libdlt.so.2: cannot open shared object file: No such file or directory

```

**Comment by Grossman1987** [comment]
okay... ;-) it was only the dependency to the dlt-daemon project
https://github.com/GENIVI/dlt-daemon
I've built it, installed it and did the ldconfig --> now it works.
Thanks! ;-)

**Comment by mmrohloff** [comment]
exactly my problem and the error message I despaired of... ldd to the library showed that it was not the lib itself that could not be opened but a dependency of the lib. Thanks for the hint!

**Comment by sincethenn** [comment]
> okay... ;-) it was only the dependency to the dlt-daemon project
> https://github.com/GENIVI/dlt-daemon
> I've built it, installed it and did the ldconfig --> now it works.
> Thanks! ;-)

I'm trying to build dlt-daemon on Mac and met following problems. Have you tried to install dlt-daemon on Mac?

**Comment by sumitpaulde** [comment]
@sincethenn I am trying to install it on mac, have you done it? I am having the same error.

**Comment by sumitpaulde** [comment]
> okay... ;-) it was only the dependency to the dlt-daemon project
> https://github.com/GENIVI/dlt-daemon
> I've built it, installed it and did the ldconfig --> now it works.
> Thanks! ;-)

Where did you install and build it? Can you please provide an explanation?

**Comment by sumitpaulde** [comment]
I hope following these bellow mentioned steps its possible to build Dlt-daemon as well as python-dlt on Mac:

1. Clone the Dlt-daemon from [here](https://github.com/GENIVI/dlt-daemon). 
2. Download the patch file [ attached](https://github.com/bmwcarit/python-dlt/files/6436307/dlt-daemon-macos2.txt) with this comment. Change the extension .patch(as it is not supported by GitHub I have added it as .txt format). 
3. Copy the dlt-daemon-macos2.patch in the Dlt-daemon directory and run `patch -p1< dlt-daemon-macos2.patch` .
4. Then follow the dlt-daemon setup [commands](https://github.com/GENIVI/dlt-daemon#build-and-install).
5. It will build the dlt-daemon but we have to follow one more step before running.
6. According to [this](https://stackoverflow.com/questions/4136181/program-using-semaphores-runs-fine-on-linux-unexpected-results-on-mac-osx) MacOs does not support unnamed semaphores, so we have to provide names for specific semaphore, in the [dlt-daemon.c](https://github.com/GENIVI/dlt-daemon/blob/master/src/daemon/dlt-daemon.c) file.
7. If you run `dlt-daemon` command from the build directory, you will see the daemon is running, although it will give some warnings.
8. To use bindings like python-dlt, we have to link it up with the dynamic library .dynlib or .so, unfortunately on my machine .so was not generating. I had to use " cmake  -DBUILD_SHARED_LIBS=OFF .." so the .dynlib was built. [More info](https://stackoverflow.com/questions/2339679/what-are-the-differences-between-so-and-dylib-on-macos)
9. At the end we have to update the [core_base.py](https://github.com/bmwcarit/python-dlt/blob/master/dlt/core/core_base.py) file,  as in the core_base.py it was dltlib = ctypes.cdll.LoadLibrary('libdlt.so.2') so we have to update it to  dltlib = ctypes.cdll.LoadLibrary('libdlt.2.18.6.dylib') or dynamically build name of the libdlt(check it in your Mac).
10.  I wonder I had to also change the name of this core_2185.py [file ](https://github.com/bmwcarit/python-dlt/blob/master/dlt/core/core_2185.pyl) to core_2180.py as I was having this error `ImportError: No module file: core_2180.py`.

I hope this helps a newbie like me!

**Comment by aigarius** [comment]
If you still have issues with latest master and 2.18.8 DLT Daemon, please open a new issue

**Comment by APoliichuk** [comment]
> I hope following these bellow mentioned steps its possible to build Dlt-daemon as well as python-dlt on Mac:
> 
> 1. Clone the Dlt-daemon from [here](https://github.com/GENIVI/dlt-daemon).
> 2. Download the patch file [ attached](https://github.com/bmwcarit/python-dlt/files/6436307/dlt-daemon-macos2.txt) with this comment. Change the extension .patch(as it is not supported by GitHub I have added it as .txt format).
> 3. Copy the dlt-daemon-macos2.patch in the Dlt-daemon directory and run `patch -p1< dlt-daemon-macos2.patch` .
> 4. Then follow the dlt-daemon setup [commands](https://github.com/GENIVI/dlt-daemon#build-and-install).
> 5. It will build the dlt-daemon but we have to follow one more step before running the dlt-daemon itself.
> 6. According to [this](https://stackoverflow.com/questions/4136181/program-using-semaphores-runs-fine-on-linux-unexpected-results-on-mac-osx) MacOs does not support unnamed semaphores, so we have to provide names for specific semaphore, in the [dlt-daemon.c](https://github.com/GENIVI/dlt-daemon/blob/master/src/daemon/dlt-daemon.c) file.
> 7. If you run `dlt-daemon` command from the build directory, you will see the daemon is running, although it will give some warnings.
> 8. To use bindings like python-dlt, we have to link it up with the dynamic library .dynlib or .so, unfortunately on my machine .so was not generating. I had to use " cmake  -DBUILD_SHARED_LIBS=OFF .." so the .dynlib was built. [More info](https://stackoverflow.com/questions/2339679/what-are-the-differences-between-so-and-dylib-on-macos)
> 9. At the end we have to update the [core_base.py](https://github.com/bmwcarit/python-dlt/blob/master/dlt/core/core_base.py) file,  as in the core_base.py it was `dltlib = ctypes.cdll.LoadLibrary('libdlt.so.2') `so we have to update it to `dltlib = ctypes.cdll.LoadLibrary('libdlt.2.18.6.dylib')`or dynamically build name of the libdlt(check it in your Mac).
> 10. I wonder I had to also change the name of this [core_2185.py](https://github.com/bmwcarit/python-dlt/blob/master/dlt/core/core_2185.pyl) file to core_2180.py as I was having this error `ImportError: No module file: core_2180.py`.
> 
> Enjoy! You have build Dlt-daemon and can start using python-dlt on you Mac.
> 
> I guess this will help a newbie like me!

@sumitpaulde 
is it possible to ask you to adjust patch provided by you the lates version of dlt-deamon repository?
Or maybe you can provide the version of dlt-deamon repository you use?
regards

**Comment by V-Mota** [comment]
Alternatively you can just install dlt-tools.

on debian systems:
`sudo apt install dlt-tools`

on rpm systems:
`sudo dnf install dlt-tools`
