### ISSUE TITLE
Get timezone from DLT

### ISSUE THREAD

**Issue by Frickenstein** [bmwcarit/python-dlt#28]
![image](https://user-images.githubusercontent.com/30051607/109174834-82939d80-7785-11eb-831d-6189f9715371.png)
In the DLTViewer it is possible to read out the logger time from a DLT file and to adjust the display.
Do you know if the time zone can be read out via the Python DLT library.

**Comment by yen3** [comment]
AFAIK, python-dlt does not similar function. If need, it's welcome to send a pull request. Thank you.
