### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by aigarius** [bmwcarit/python-dlt#4]
As of this moment this does not work with Python 3 - there are reguler bytes/strings issues, but even with them fixed there are some issues with memory management that need a deeper look. The work is ongoing.

**Comment by joaodasousa** [comment]
Seems like preloading libtcmalloc_minimal lib "solves" some of the mem issues.
> apt-get update libtcmalloc-minimal4
> export LD_PRELOAD="/usr/lib/libtcmalloc_minimal.so.4"

Do you have experience with this?

**Comment by aigarius** [comment]
Fixed in the new version
